"""
Staff and Branch Lookup Tables extracted from Staff Listing.xlsx.
Maps operator codes (e.g. LT7) to full names (e.g. Leonardo Tutaan)
and branch codes (e.g. SY1) to full branch names.
"""

OPERATOR_NAMES = {
    'ASI': 'AAW Sydney Import LCL', 'AF2': 'Abby Feng', 'AH1': 'Adam Hughes',
    'ADL': 'ADL - Branch Account', 'AKL': 'AKL - Branch Account', 'AD1': 'Alberto DiMaggio',
    'AC6': 'Aleeta Carnelio', 'AMN': 'Alex McNairn', 'AM1': 'Alexa Murrin',
    'AC8': 'Alfred Chen', 'AW2': 'Alicia Welch', 'AM2': 'Andy May',
    'AD2': 'Anh Dang', 'AF': 'Anna Thompson', 'AC5': 'Anthony Cull',
    'AC7': 'Aubrey Contreras', 'AAA': 'Auditor', 'BR5': 'Beata Ratowska',
    'BS': 'Blake Strangwick', 'HOY': 'BLL - Branch Account', 'BLL': 'BLL - Branch Account',
    'BNE': 'BNE - Branch Account', 'BL3': 'Brett Leal', 'BM1': 'Briannon Mott',
    'CM3': 'Callum Mohr', 'CS2': 'Caroline Solotuchin', 'CC4': 'Catherine Cruz',
    'CBR': 'CBR - Branch Account', 'CC3': 'Cedrick Cruz', 'CG7': 'Chamila Gunetilleke',
    'CF2': 'Charito Falcon', 'AAB': 'Claire Brotherton', 'CE': 'Clinton Eckersall',
    'CZ1': 'Conzentus Admin', 'C01': 'Cozentus1', 'C02': 'Cozentus2',
    'C03': 'Cozentus3', 'C04': 'Cozentus4', 'DS7': 'Daisyrie Silerio',
    'DK1': 'Damira Kadiric', 'DW': 'Daniel Wang', 'DB1': 'Darren Bennett',
    'DG7': 'Dave Anthony Gomez', 'DL2': 'David Laurie', 'DP5': 'David Peake',
    'DC2': 'Davina Cameron', 'DW7': 'Deneal Whitehouse', 'DF1': 'Diana Zambrano Fino',
    'ET1': 'Elicit Technology 1', 'ET2': 'Elicit Technology 2', 'EA2': 'Elizalde Aragon',
    'EY1': 'Ellie Yeom', 'EQ1': 'Emma Qian', 'EC2': 'Esther Cheng',
    'FC4': 'Fernanda C Sarzi', 'FS1': 'Francis Su', 'FJ1': 'Francy Javela',
    'FRE': 'FRE - Branch Account', 'FF1': 'Freightify Admin', 'GK': 'Gareth Knight',
    'GB1': 'Gerald Bucio', 'JL2': 'Ginalyn Lu', 'GM1': 'Grace Mendoza',
    'HW1': 'Hellen Wang', 'HR1': 'Herschelle Rafinian', 'IB1': 'Iesha Bridle',
    'IW1': 'Ivy Wong', 'JK1': 'James Kurz', 'JO1': 'Janine Ocillos',
    'JP0': 'Jason Pretorius', 'JG7': 'Jennifer Garces', 'JD': 'Jessica Doyle',
    'JK2': 'Jessica Kawana', 'JP': 'Jiri Pelc', 'JM8': 'Jitu Mogre',
    'JDM': 'Joe Di Monaco', 'JE1': 'John Eid', 'JZ1': 'John Zhang',
    'JC3': 'Josephine Chan', 'JI1': 'Josievil Intan', 'JJ2': 'Judy Jiang',
    'JN8': 'Julie Neoh', 'JZ2': 'Julie Zhu', 'JG1': 'Justine Kimberly Gacura',
    'KN1': 'Kai Nguyen', 'KD1': 'Kane Dunleavy', 'KL4': 'Karen Mae Lasprilla',
    'KL5': 'Karla Labastin', 'KS1': 'Karolina Stjepovic', 'KS2': 'Kasey Shvetcova',
    'KC3': 'Kate Chace', 'KR1': 'Kathryn Reynolds', 'KB2': 'Kelly Baugh',
    'KR4': 'Kelsey Reich', 'KL3': 'Kelvin Liu', 'KB3': 'Kenneth Bermio',
    'KC': 'Kim Carningham', 'KM1': 'Kim Lam', 'KN2': 'Kylea Nobre',
    'KC7': 'Kylie Carlson', 'LN1': 'Lawrence Nellas', 'LV2': 'Le Vo',
    'LP1': 'Leah Purvis', 'LT7': 'Leonardo Tutaan', 'LXB': 'Logixboard Control',
    'LB9': 'Lorena Butler', 'MS2': 'Manilyn Sibonga', 'MW2': 'Mareta Chang Wai',
    'MM3': 'Maria Michelle Mejala', 'MD2': 'Mariela Monica Dalena', 'MK2': 'Marwan Kallas',
    'MT4': 'Mary Ann Tado', 'MP1': 'Mary Anne Paulino', 'MT1': 'Matt Treeby',
    'MB3': 'Matthew Broadhurst', 'MM7': 'Matthew Martin', 'MT3': 'Matthew Thorburn',
    'MK1': 'Mayra Kazakeviche', 'MEL': 'MEL - Branch Account', 'MHA': 'Melbourne House Account',
    'MC1': 'Michelle Joana Castillo', 'MA4': 'Mitha Amin', 'MG1': 'Myra Guelos',
    'NT1': 'Namalie Tirimanne', 'ND': 'Nataly Daza', 'NB4': 'Nicole Bilson',
    'NOM': 'Nominated by OS Agent', 'OX': 'Oliver Xie', 'PMR': 'Peter Morley',
    'PL2': 'Priscilla Ly', 'PRJ': 'PRJ - Branch Account', 'QB1': 'Quennie Valerie Bordeos',
    'RC': 'Rachael Christie', 'RP2': 'Renuka Priyadarshani', 'RJ0': 'Rhys Jones',
    'RT1': 'Rogel Ponce Tejada', 'RR2': 'Rommel Ramos', 'SC5': 'Sam Chea',
    'ST1': 'Samantha Ciappina', 'ST2': 'Sandra Valencia Trejos', 'SB': 'Sara Bu',
    'SL8': 'Scott Leal', 'SDA': 'Sean De Asis', 'SW1': 'Selina Wang',
    'ST4': 'Shalindra Thenuwara', 'SR4': 'Shanil Rathore', 'SZ1': 'Sharon Zhang',
    'SC1': 'Sheila Cancio', 'SA7': 'Shiela Mae Apostol', 'SC0': 'Stephen Collins',
    'SH4': 'Stephen Hearty', 'SD1': 'Steven Docherty', 'SM2': 'Steven Markovski',
    'SE1': 'Stuart Eastaugh', 'SYD': 'SYD - Branch Account', 'TW': 'Teresa Weir',
    'TT2': 'Tia-Rose Tootell', 'TC1': 'Tim Cahill', 'VE1': 'Virginia Erica',
    'OR1': 'Vittorio Renong', 'VV1': 'Vivian Valero', 'WN': 'Wesley Neilson',
    'WG1': 'Will Gowers', 'WC1': 'William Chan'
}

BRANCH_NAMES = {
    'SY1': 'AAW Global Logistics - Sydney',
    'SYD': 'AAW Global Logistics - Sydney',
    'ME1': 'AAW Global Logistics - Melbourne',
    'MEL': 'AAW Global Logistics - Melbourne',
    'BN1': 'AAW Global Logistics - Brisbane',
    'BNE': 'AAW Global Logistics - Brisbane',
    'AD1': 'AAW Global Logistics - Adelaide',
    'ADL': 'AAW Global Logistics - Adelaide',
    'FR1': 'AAW Global Logistics - Fremantle',
    'FRE': 'AAW Global Logistics - Fremantle',
    'AKL': 'AAW Global Logistics - Auckland',
    'HOZ': 'AAW Global Logistics - Auckland',
    'BR1': 'AAW Customs Brokerage',
    'BRK': 'AAW Customs Brokerage',
    'PR1': 'AAW Project Logistics',
    'PRJ': 'AAW Project Logistics',
    'BLL': 'AAW Bulk Liquid Logistics',
    'HOY': 'AAW Bulk Liquid Logistics',
    'HLA': 'Hoyer Logistics Australia',
    'CBG': 'Coastalbridge',
    'CBR': 'Coastalbridge',
    'CCC': 'CoastalBridge Agencies for COSCO Shipping',
    'TFS': 'Coastalbridge Agencies for Toyofuji Shipping',
    'PIL': 'PIL Logistics Australia',
    'MIL': 'Regional Shipping Services',
    'HAU': 'AAW Group Holdings',
    'HDO': 'AAW Group Holdings',
}

OPERATOR_BRANCHES = {
    # Adelaide
    'KB2': 'AAW Global Logistics - Adelaide', 'Kelly Baugh': 'AAW Global Logistics - Adelaide',
    'KC': 'AAW Global Logistics - Adelaide', 'Kim Carningham': 'AAW Global Logistics - Adelaide',
    'DP5': 'AAW Global Logistics - Adelaide', 'David Peake': 'AAW Global Logistics - Adelaide',
    'HW1': 'AAW Global Logistics - Adelaide', 'Hellen Wang': 'AAW Global Logistics - Adelaide',
    'LE': 'AAW Global Logistics - Adelaide', 'Lina Emelianova': 'AAW Global Logistics - Adelaide',
    'ADL': 'AAW Global Logistics - Adelaide', 'ADL - Branch Account': 'AAW Global Logistics - Adelaide',

    # Melbourne
    'SDA': 'AAW Global Logistics - Melbourne', 'Sean De Asis': 'AAW Global Logistics - Melbourne',

    # Fremantle
    'SL2': 'AAW Global Logistics - Fremantle', 'Stella Lee': 'AAW Global Logistics - Fremantle',
    'JP': 'AAW Global Logistics - Fremantle', 'Jiri Pelc': 'AAW Global Logistics - Fremantle',
    'IB1': 'AAW Global Logistics - Fremantle', 'Iesha Bridle': 'AAW Global Logistics - Fremantle',
    'GK': 'AAW Global Logistics - Fremantle', 'Gareth Knight': 'AAW Global Logistics - Fremantle',
    'LV2': 'AAW Global Logistics - Fremantle', 'Le Vo': 'AAW Global Logistics - Fremantle',
    'AW2': 'AAW Global Logistics - Fremantle', 'Alicia Welch': 'AAW Global Logistics - Fremantle',
    'FRE': 'AAW Global Logistics - Fremantle', 'FRE - Branch Account': 'AAW Global Logistics - Fremantle',

    # Auckland
    'AAB': 'AAW Global Logistics - Auckland', 'Claire Brotherton': 'AAW Global Logistics - Auckland',
    'KN1': 'AAW Global Logistics - Auckland', 'Kai Nguyen': 'AAW Global Logistics - Auckland',
    'LP1': 'AAW Global Logistics - Auckland', 'Leah Purvis': 'AAW Global Logistics - Auckland',
    'SM7': 'AAW Global Logistics - Auckland', 'Sina Meleisea': 'AAW Global Logistics - Auckland',
    'JM8': 'AAW Global Logistics - Auckland', 'Jitu Mogre': 'AAW Global Logistics - Auckland',
    'CN': 'AAW Global Logistics - Auckland', 'Carol Ngo': 'AAW Global Logistics - Auckland',
    'LV1': 'AAW Global Logistics - Auckland', 'Louise Venables': 'AAW Global Logistics - Auckland',
    'MW2': 'AAW Global Logistics - Auckland', 'Mareta Chang Wai': 'AAW Global Logistics - Auckland',
    'AKL': 'AAW Global Logistics - Auckland', 'AKL - Branch Account': 'AAW Global Logistics - Auckland',
}
